/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/alertas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar
         * @description List all alerts, optionally filtered by estado.
         *
         *     Valid valores: nueva, en_analisis, propuesta, aprobada, rechazada, ejecutada
         */
        get: operations["listar_alertas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alertas/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Obtener */
        get: operations["obtener_alertas__id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/alertas/{id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decidir */
        post: operations["decidir_alertas__id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sesion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sesion */
        get: operations["sesion_auth_sesion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bandeja/resumen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Totales
         * @description The inbox totals over the proposed alerts, each with the query that produced it.
         */
        get: operations["totales_bandeja_resumen_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/bitacora": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar
         * @description Get audit log (bitácora) of alert lifecycle events, optionally filtered by alert and event type.
         */
        get: operations["listar_bitacora_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/configuracion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Leer */
        get: operations["leer_configuracion_get"];
        /** Guardar */
        put: operations["guardar_configuracion_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/consultas/{query_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Obtener
         * @description The query that produced a figure, as the API recorded it when the figure was cited.
         */
        get: operations["obtener_consultas__query_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interno/alertas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Crear Alerta
         * @description Vigía crea una nueva alerta.
         *     La alerta nace en estado 'new' y entra inmediatamente en análisis por Analista.
         */
        post: operations["crear_alerta_interno_alertas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interno/alertas/{id}/causa": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Ingresar Causa
         * @description Analista explica la causa.
         *     Transición: new → analyzing.
         *     El texto de la causa es enmascarado antes de ser enviado al modelo,
         *     pero se almacena sin enmascarar.
         */
        put: operations["ingresar_causa_interno_alertas__id__causa_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interno/alertas/{id}/ejecutar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ejecutar Accion
         * @description Ejecutor corre una acción aprobada.
         *     Transición: approved → executed.
         */
        post: operations["ejecutar_accion_interno_alertas__id__ejecutar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interno/alertas/{id}/propuesta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Ingresar Propuesta
         * @description Estratega propone acciones.
         *     Transición: analyzing → proposed.
         */
        put: operations["ingresar_propuesta_interno_alertas__id__propuesta_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulacion/avanzar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Avanzar */
        post: operations["avanzar_simulacion_avanzar_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/simulacion/dia-actual": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dia Actual
         * @description Get the current simulated day.
         *     Used by Vigía to know what date to filter queries by.
         */
        get: operations["dia_actual_simulacion_dia_actual_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Action
         * @description Proposed mitigation action with impact and parameters.
         */
        "Action-Input": {
            /** @description Confidence in the action's effectiveness */
            confidence: components["schemas"]["Confidence-Input"];
            /** @description Detailed action description with impact figures */
            description: components["schemas"]["Sentence-Input"];
            /**
             * Id
             * @description Unique action ID
             * @example action_raise_price_3pct
             */
            id: string;
            /** @description Expected business impact if executed */
            impact?: components["schemas"]["Impact"] | null;
            /**
             * Parameters
             * @description Editable parameters (price, qty, etc.)
             */
            parameters?: {
                [key: string]: string | number;
            };
            /**
             * Title
             * @description Short action title
             */
            title: string;
            /**
             * Type
             * @description Type: email_draft, task, purchase_order_draft, or price_change_draft
             * @enum {string}
             */
            type: "email_draft" | "task" | "purchase_order_draft" | "price_change_draft";
        };
        /**
         * Action
         * @description Proposed mitigation action with impact and parameters.
         */
        "Action-Output": {
            /** @description Confidence in the action's effectiveness */
            confidence: components["schemas"]["Confidence-Output"];
            /** @description Detailed action description with impact figures */
            description: components["schemas"]["Sentence-Output"];
            /**
             * Id
             * @description Unique action ID
             * @example action_raise_price_3pct
             */
            id: string;
            /** @description Expected business impact if executed */
            impact: components["schemas"]["Impact"] | null;
            /**
             * Parameters
             * @description Editable parameters (price, qty, etc.)
             */
            parameters: {
                [key: string]: string | number;
            };
            /**
             * Title
             * @description Short action title
             */
            title: string;
            /**
             * Type
             * @description Type: email_draft, task, purchase_order_draft, or price_change_draft
             * @enum {string}
             */
            type: "email_draft" | "task" | "purchase_order_draft" | "price_change_draft";
        };
        /**
         * ActorAgent
         * @description Alert action performed by an agent.
         */
        ActorAgent: {
            /**
             * Agent
             * @description Agent name (vigia, analista, estratega, ejecutor, chat)
             * @enum {string}
             */
            agent: "vigia" | "analista" | "estratega" | "ejecutor" | "chat";
            /**
             * @description Discriminator: action by agent (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            kind: "agent";
        };
        /**
         * ActorPerson
         * @description Alert decision made by a human.
         */
        ActorPerson: {
            /**
             * @description Discriminator: action by person (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            kind: "person";
            /**
             * Name
             * @description Name of the person signed in
             */
            name: string;
            /**
             * Role
             * @description Person role (gerente, lider_proceso, analista, auditor)
             */
            role: string;
        };
        /**
         * AdvanceEnd
         * @description Final event of the simulated clock's advance stream.
         */
        AdvanceEnd: {
            /**
             * Newalerts
             * @description IDs of the alerts raised on that day
             */
            newAlerts: string[];
            /**
             * Simulatedday
             * @description Simulated day the clock reached (ISO 8601)
             */
            simulatedDay: string;
        };
        /**
         * AgentAlertInput
         * @description Vigía input: new alert detected from metric anomaly.
         */
        AgentAlertInput: {
            /** @description Confidence in the alert detection */
            confidence: components["schemas"]["Confidence-Input"];
            /**
             * Metric
             * @description Metric that triggered alert
             * @enum {string}
             */
            metric: "margen_pct" | "saldo_vencido" | "dias_pago_prom" | "cobertura_dias" | "descuento_en_exceso" | "veces_intervalo_habitual";
            /** @description Pesos at risk (COP) */
            pesosAtRisk: components["schemas"]["Figure"];
            /** @description Monthly recovery potential */
            recoverablePerMonth?: components["schemas"]["Figure"] | null;
            /**
             * Severity
             * @description Alert severity (critical, high, medium, low)
             * @enum {string}
             */
            severity: "critical" | "high" | "medium" | "low";
            /**
             * Simulateddate
             * @description Simulated date of detection (ISO 8601)
             */
            simulatedDate: string;
            /** @description Alert title with figures */
            title: components["schemas"]["Sentence-Input"];
        };
        /**
         * AgentCauseInput
         * @description Analista input: root cause explanation with evidence.
         */
        AgentCauseInput: {
            /**
             * Cause
             * @description Root cause (identified or no_evidence)
             */
            cause: components["schemas"]["CauseIdentified-Input"] | components["schemas"]["CauseNoEvidence-Input"];
            /**
             * Evidence
             * @description Additional evidence queries run by Analista
             */
            evidence?: components["schemas"]["Evidence-Input"][];
        };
        /**
         * AgentExecutionInput
         * @description Ejecutor input: result of executing an approved action.
         */
        AgentExecutionInput: {
            /**
             * Actionid
             * @description ID of the action executed
             */
            actionId: string;
            /**
             * Error
             * @description Detailed error if status != success
             */
            error?: string | null;
            /**
             * Result
             * @description Human-readable result or error message
             */
            result: string;
            /**
             * Status
             * @description Execution result
             * @enum {string}
             */
            status: "success" | "failed" | "partial";
        };
        /**
         * AgentProposalInput
         * @description Estratega input: proposed mitigation actions.
         */
        AgentProposalInput: {
            /**
             * Actions
             * @description 1-3 proposed actions with impact and parameters
             */
            actions: components["schemas"]["Action-Input"][];
        };
        /**
         * AgentStep
         * @description Progress event during agent processing (for SSE streams).
         */
        AgentStep: {
            /**
             * Agent
             * @description Agent name
             * @enum {string}
             */
            agent: "vigia" | "analista" | "estratega" | "ejecutor" | "chat";
            /**
             * Alertid
             * @description Alert ID being processed
             * @default null
             */
            alertId: string | null;
            /**
             * Description
             * @description Human-readable step description
             */
            description: string;
            /**
             * End
             * @description UTC end time (ISO 8601), null if running
             * @default null
             */
            end: string | null;
            /**
             * Node
             * @description Node of the decision tree the step walked, if any
             * @default null
             */
            node: string | null;
            /**
             * Start
             * @description UTC start time (ISO 8601)
             */
            start: string;
            /**
             * Status
             * @description Step status
             * @enum {string}
             */
            status: "running" | "done";
        };
        /**
         * Alert
         * @description Complete alert lifecycle state.
         */
        Alert: {
            /**
             * Actions
             * @description Proposed mitigation actions
             */
            actions: components["schemas"]["Action-Output"][];
            /**
             * Candecide
             * @description Whether the person signed in may decide this alert, computed per request and never stored
             * @default false
             */
            canDecide: boolean;
            /**
             * Cause
             * @description Root cause (identified with evidence or no_evidence)
             */
            cause: components["schemas"]["CauseIdentified-Output"] | components["schemas"]["CauseNoEvidence-Output"];
            /**
             * Changesrequested
             * @description Whether a person asked for changes to the proposal
             * @default false
             */
            changesRequested: boolean;
            /** @description Confidence in the alert detection */
            confidence: components["schemas"]["Confidence-Output"];
            /**
             * Decidedby
             * @description Who decides this alert: the area that owns its metric, or Gerencia when no area owns it
             */
            decidedBy: string | null;
            /** @description Action executed (only when status=executed) */
            executedAction: components["schemas"]["ExecutedAction"] | null;
            /**
             * Id
             * @description Unique alert ID
             * @example alerta_abc123def456
             */
            id: string;
            /**
             * Labels
             * @description Identity labels a person reads, the metric's short name first then the affected entity (e.g. ['Margen', 'línea Hogar'])
             */
            labels: string[];
            /**
             * Mergedalerts
             * @description Alerts merged into this one
             */
            mergedAlerts: components["schemas"]["MergedAlert"][];
            /**
             * Mergedinto
             * @description ID of the alert this one was merged into
             */
            mergedInto: string | null;
            /**
             * Metric
             * @description Metric that triggered this alert
             * @enum {string}
             */
            metric: "margen_pct" | "saldo_vencido" | "dias_pago_prom" | "cobertura_dias" | "descuento_en_exceso" | "veces_intervalo_habitual";
            /** @description Pesos at risk (COP) */
            pesosAtRisk: components["schemas"]["Figure"];
            /** @description Potential monthly recovery if action taken */
            recoverablePerMonth: components["schemas"]["Figure"] | null;
            /**
             * Severity
             * @description Alert severity: critical, high, medium, or low
             * @enum {string}
             */
            severity: "critical" | "high" | "medium" | "low";
            /**
             * Simulateddate
             * @description Simulated date when alert was created (ISO 8601)
             */
            simulatedDate: string;
            /**
             * Status
             * @description Current status in lifecycle: new → analyzing → proposed → approved/rejected → executed
             * @enum {string}
             */
            status: "new" | "analyzing" | "proposed" | "approved" | "rejected" | "executed" | "merged";
            /** @description Alert title with initial impact figures */
            title: components["schemas"]["Sentence-Output"];
        };
        /**
         * AlertEstadoEnum
         * @description Valid alert estado values (Spanish names for API contract).
         * @enum {string}
         */
        AlertEstadoEnum: "nueva" | "en_analisis" | "propuesta" | "aprobada" | "rechazada" | "ejecutada" | "unida";
        /**
         * CauseIdentified
         * @description Root cause found with evidence.
         */
        "CauseIdentified-Input": {
            /**
             * Evidence
             * @description Supporting evidence
             */
            evidence: components["schemas"]["Evidence-Input"][];
            /**
             * @description Discriminator: cause was identified (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            kind: "identified";
            /** @description Root cause statement with figures */
            sentence: components["schemas"]["Sentence-Input"];
        };
        /**
         * CauseIdentified
         * @description Root cause found with evidence.
         */
        "CauseIdentified-Output": {
            /**
             * Evidence
             * @description Supporting evidence
             */
            evidence: components["schemas"]["Evidence-Output"][];
            /**
             * @description Discriminator: cause was identified (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            kind: "identified";
            /** @description Root cause statement with figures */
            sentence: components["schemas"]["Sentence-Output"];
        };
        /**
         * CauseNoEvidence
         * @description Root cause could not be identified with available data.
         */
        "CauseNoEvidence-Input": {
            /**
             * @description Discriminator: cause could not be identified (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            kind: "no_evidence";
            /**
             * Queriesreviewed
             * @description Query IDs that were searched
             */
            queriesReviewed?: string[];
            /**
             * Reason
             * @description Explanation why cause could not be determined
             */
            reason: string;
        };
        /**
         * CauseNoEvidence
         * @description Root cause could not be identified with available data.
         */
        "CauseNoEvidence-Output": {
            /**
             * @description Discriminator: cause could not be identified (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            kind: "no_evidence";
            /**
             * Queriesreviewed
             * @description Query IDs that were searched
             */
            queriesReviewed: string[];
            /**
             * Reason
             * @description Explanation why cause could not be determined
             */
            reason: string;
        };
        /**
         * ChatMessage
         * @description Chat response from Centinela (the agent chat).
         */
        ChatMessage: {
            /**
             * Alertid
             * @description Related alert ID if any
             * @default null
             */
            alertId: string | null;
            /**
             * Date
             * @description Message timestamp (ISO 8601)
             */
            date: string;
            /**
             * Enoughevidence
             * @description Whether answer is based on sufficient evidence
             */
            enoughEvidence: boolean;
            /**
             * Figures
             * @description Numeric evidence in the message
             */
            figures: components["schemas"]["Figure"][];
            /**
             * Id
             * @description Message ID
             */
            id: string;
            /**
             * Outcome
             * @description How the walk of conversar ended: answered, no_evidence, out_of_scope or refused
             * @default answered
             * @enum {string}
             */
            outcome: "answered" | "no_evidence" | "out_of_scope" | "refused";
            /**
             * Role
             * @description Message source: user question or centinela answer
             * @enum {string}
             */
            role: "user" | "centinela";
            /**
             * Series
             * @description Historical series if relevant
             * @default null
             */
            series: components["schemas"]["SeriesPoint"][] | null;
            /**
             * Text
             * @description Message text
             */
            text: string;
        };
        /**
         * ChatQuestion
         * @description User question for Centinela (the agent chat).
         */
        ChatQuestion: {
            /**
             * Alertid
             * @description Alert the question is asked from, if any
             */
            alertId?: string | null;
            /**
             * Question
             * @description Natural language question about alert or metric
             */
            question: string;
        };
        /**
         * Confidence
         * @description Confidence assessment with assumptions.
         */
        "Confidence-Input": {
            /**
             * Assumptions
             * @description Assumptions underlying the confidence assessment
             */
            assumptions?: string[];
            /**
             * Level
             * @description Confidence level: high, medium, or low
             * @enum {string}
             */
            level: "high" | "medium" | "low";
        };
        /**
         * Confidence
         * @description Confidence assessment with assumptions.
         */
        "Confidence-Output": {
            /**
             * Assumptions
             * @description Assumptions underlying the confidence assessment
             */
            assumptions: string[];
            /**
             * Level
             * @description Confidence level: high, medium, or low
             * @enum {string}
             */
            level: "high" | "medium" | "low";
        };
        /**
         * Credenciales
         * @description Email and password a person signs in with.
         */
        Credenciales: {
            /**
             * Email
             * @description Sign-in email
             */
            email: string;
            /**
             * Password
             * @description Password
             */
            password: string;
        };
        /**
         * DecisionApprove
         * @description Human decision: approve and execute action.
         */
        DecisionApprove: {
            /**
             * Actionid
             * @description ID of action to approve
             */
            actionId: string;
            /**
             * @description Discriminator: approve decision (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            kind: "approve";
        };
        /**
         * DecisionEdit
         * @description Human decision: approve with modified parameters.
         */
        DecisionEdit: {
            /**
             * Actionid
             * @description ID of action to modify and approve
             */
            actionId: string;
            /**
             * @description Discriminator: edit and approve decision (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            kind: "edit";
            /**
             * Parameters
             * @description Modified parameters (price, qty, etc.)
             */
            parameters: {
                [key: string]: string | number;
            };
        };
        /**
         * DecisionReject
         * @description Human decision: reject alert.
         */
        DecisionReject: {
            /**
             * @description Discriminator: reject decision (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            kind: "reject";
            /**
             * Reason
             * @description Reason for rejection
             */
            reason: string;
        };
        /**
         * DecisionRequestChanges
         * @description Human decision: ask Estratega to propose again with a reason.
         */
        DecisionRequestChanges: {
            /**
             * @description Discriminator: request changes decision (enum property replaced by openapi-typescript)
             * @enum {string}
             */
            kind: "request_changes";
            /**
             * Reason
             * @description What the person wants changed in the proposal
             */
            reason: string;
        };
        /**
         * Evidence
         * @description Supporting data for a claim: statement + historical series.
         */
        "Evidence-Input": {
            /** @description Statement with figures */
            claim: components["schemas"]["Sentence-Input"];
            /**
             * Queryid
             * @description SQL query ID that retrieved this evidence
             */
            queryId: string;
            /**
             * Series
             * @description Historical series supporting the claim
             */
            series?: components["schemas"]["SeriesPoint"][] | null;
        };
        /**
         * Evidence
         * @description Supporting data for a claim: statement + historical series.
         */
        "Evidence-Output": {
            /** @description Statement with figures */
            claim: components["schemas"]["Sentence-Output"];
            /**
             * Queryid
             * @description SQL query ID that retrieved this evidence
             */
            queryId: string;
            /**
             * Series
             * @description Historical series supporting the claim
             */
            series: components["schemas"]["SeriesPoint"][] | null;
        };
        /**
         * ExecutedAction
         * @description Result of executing an approved action.
         */
        ExecutedAction: {
            /**
             * Actionid
             * @description ID of the executed action
             */
            actionId: string;
            /**
             * Result
             * @description Execution outcome: success, failed, or partial
             */
            result: string;
        };
        /**
         * Figure
         * @description Quantitative measurement with unit and traceability.
         */
        Figure: {
            /**
             * Queryid
             * @description Reference to SQL query that produced this figure
             */
            queryId: string;
            /**
             * Unit
             * @description Unit of measurement (COP, percent, days, etc.)
             * @enum {string}
             */
            unit: "COP" | "points" | "percent" | "days" | "units";
            /**
             * Value
             * @description Numeric value
             * @example 42000000
             */
            value: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Impact
         * @description Expected business impact of an action.
         */
        Impact: {
            /** @description Impact magnitude (pesos, percent, etc.) */
            figure: components["schemas"]["Figure"];
            /**
             * Period
             * @description Recurrence: monthly or one-time
             * @enum {string}
             */
            period: "month" | "once";
        };
        /**
         * InboxSummary
         * @description The three totals of the inbox, computed over the proposed alerts.
         */
        InboxSummary: {
            /** @description Pesos at risk summed over the proposed alerts */
            moneyAtRisk: components["schemas"]["Figure"];
            /** @description Proposed alerts awaiting a decision */
            pendingDecisions: components["schemas"]["Figure"];
            /** @description Pesos recoverable per month summed over the proposed alerts */
            recoverablePerMonth: components["schemas"]["Figure"];
        };
        /**
         * LogEvent
         * @description Audit log entry for alert lifecycle event.
         */
        LogEvent: {
            /**
             * Actor
             * @description Who/what performed the action (agent or person)
             */
            actor: components["schemas"]["ActorAgent"] | components["schemas"]["ActorPerson"];
            /**
             * Alertid
             * @description Alert ID, null for a chat question asked from no alert
             */
            alertId: string | null;
            /**
             * Date
             * @description UTC timestamp of event (ISO 8601)
             */
            date: string;
            /**
             * Detail
             * @description Human-readable description or JSON cost data
             */
            detail: string;
            /**
             * Id
             * @description Log entry ID
             */
            id: string;
            /**
             * Queryid
             * @description SQL query ID if relevant to this event
             */
            queryId: string | null;
            /**
             * Simulatedday
             * @description Simulated date when event occurred
             */
            simulatedDay: string;
            /**
             * Type
             * @description Event type: alert, evidence, proposal, decision, action, result, question, answer, refusal, configuracion
             * @enum {string}
             */
            type: "alert" | "evidence" | "proposal" | "decision" | "action" | "result" | "question" | "answer" | "refusal" | "configuracion";
        };
        /**
         * MergedAlert
         * @description Summary of an alert folded into another.
         */
        MergedAlert: {
            /**
             * Cause
             * @description Cause of the merged alert
             */
            cause: components["schemas"]["CauseIdentified-Output"] | components["schemas"]["CauseNoEvidence-Output"];
            /**
             * Id
             * @description ID of the merged alert
             */
            id: string;
            /**
             * Metric
             * @description Metric of the merged alert
             * @enum {string}
             */
            metric: "margen_pct" | "saldo_vencido" | "dias_pago_prom" | "cobertura_dias" | "descuento_en_exceso" | "veces_intervalo_habitual";
            /** @description Pesos at risk of the merged alert (COP) */
            pesosAtRisk: components["schemas"]["Figure"];
            /**
             * Simulateddate
             * @description Simulated date of the merged alert (ISO 8601)
             */
            simulatedDate: string;
            /** @description Title of the merged alert */
            title: components["schemas"]["Sentence-Output"];
        };
        /**
         * Persona
         * @description The person signed in, read from the profiles of the root .env.
         */
        Persona: {
            /**
             * Area
             * @description Area a lider_proceso leads, as the owners of a metric name it; null for every other role
             */
            area: string | null;
            /**
             * Email
             * @description Sign-in email, lowercase
             */
            email: string;
            /**
             * Name
             * @description Name the bitácora records
             */
            name: string;
            /**
             * Role
             * @description Role: gerente, lider_proceso, analista or auditor
             * @enum {string}
             */
            role: "gerente" | "lider_proceso" | "analista" | "auditor";
        };
        /**
         * Query
         * @description The query that produced a figure: a kernel call an agent ran, or a sum over the stored alerts.
         */
        Query: {
            /**
             * Description
             * @description What the query reads and the simulated day it was read on
             */
            description: string;
            /**
             * Id
             * @description The figure's queryId
             */
            id: string;
            /**
             * Source
             * @description Where the query runs: the KPI kernel of packages/tools, or the stored alerts
             * @default kernel
             * @enum {string}
             */
            source: "kernel" | "alertas";
            /**
             * Sql
             * @description The kernel call or the SQL over the stored alerts that returned the figure
             */
            sql: string;
        };
        /**
         * Sentence
         * @description Natural language statement with optional supporting figures.
         */
        "Sentence-Input": {
            /**
             * Figures
             * @description Numeric evidence supporting the statement
             */
            figures?: components["schemas"]["Figure"][];
            /**
             * Text
             * @description Human-readable statement
             */
            text: string;
        };
        /**
         * Sentence
         * @description Natural language statement with optional supporting figures.
         */
        "Sentence-Output": {
            /**
             * Figures
             * @description Numeric evidence supporting the statement
             */
            figures: components["schemas"]["Figure"][];
            /**
             * Text
             * @description Human-readable statement
             */
            text: string;
        };
        /**
         * SeriesPoint
         * @description Single data point in a time series.
         */
        SeriesPoint: {
            /**
             * Date
             * @description ISO 8601 date
             * @example 2026-10-01
             */
            date: string;
            /**
             * Value
             * @description Value at this date
             */
            value: number;
        };
        /**
         * Sesion
         * @description A signed session token and the person it belongs to.
         */
        Sesion: {
            /** @description The person signed in */
            persona: components["schemas"]["Persona"];
            /**
             * Token
             * @description Bearer token, valid for eight hours
             */
            token: string;
        };
        /**
         * Settings
         * @description What Centinela watches, who decides each metric and how far each action type goes.
         */
        Settings: {
            /**
             * Autonomy
             * @description Per action type: inform, propose, or execute, which the pilot refuses
             */
            autonomy: {
                [key: string]: "inform" | "propose" | "execute";
            };
            /**
             * Metrics
             * @description The API's metrics, in the order of data/metricas.yaml
             */
            metrics: components["schemas"]["WatchedMetric"][];
            /**
             * Owners
             * @description The areas that can own a metric: those a lider_proceso profile leads
             */
            owners: string[];
        };
        /**
         * SimulatedDay
         * @description Current simulated day in ISO 8601 format.
         */
        SimulatedDay: {
            /**
             * Dia
             * @description Current simulated day (YYYY-MM-DD)
             * @example 2026-10-03
             */
            dia: string;
        };
        /**
         * Threshold
         * @description One entry of a metric's umbrales in data/metricas.yaml.
         */
        Threshold: {
            /**
             * Editable
             * @description Whether a person may change it: only a threshold that is one number
             */
            editable: boolean;
            /**
             * Key
             * @description The threshold's key, the KPI column it compares, e.g. caida_pts
             */
            key: string;
            /**
             * Label
             * @description What the threshold measures, as a person reads it
             */
            label: string;
            /**
             * Rule
             * @description The threshold as data/metricas.yaml states it, in Spanish
             */
            rule: string;
            /**
             * Value
             * @description The value in force when the threshold is one number; null when it is read from a column or by class
             */
            value: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * WatchedMetric
         * @description A metric of the API, whether Centinela watches it, its thresholds and who owns it.
         */
        WatchedMetric: {
            /**
             * Description
             * @description What the metric measures, its descripcion
             */
            description: string;
            /**
             * Metric
             * @description The metric
             * @enum {string}
             */
            metric: "margen_pct" | "saldo_vencido" | "dias_pago_prom" | "cobertura_dias" | "descuento_en_exceso" | "veces_intervalo_habitual";
            /**
             * Name
             * @description Short name, the etiqueta of data/metricas.yaml
             */
            name: string;
            /**
             * Owner
             * @description The area whose process leader decides its alerts; null when only the gerente does
             */
            owner: string | null;
            /**
             * Rule
             * @description When it alerts, its umbral_alerta
             */
            rule: string;
            /**
             * Source
             * @description Where its thresholds come from, its fuente_umbral
             */
            source: string;
            /**
             * Thresholds
             * @description Its thresholds, one per entry of its umbrales
             */
            thresholds: components["schemas"]["Threshold"][];
            /**
             * View
             * @description The semantic view it is read from
             */
            view: string;
            /**
             * Watched
             * @description Whether the day run raises alerts of this metric
             */
            watched: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listar_alertas_get: {
        parameters: {
            query?: {
                /** @description Filter by alert estado (Spanish name for status) */
                estado?: components["schemas"]["AlertEstadoEnum"] | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_alertas__id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decidir_alertas__id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionApprove"] | components["schemas"]["DecisionEdit"] | components["schemas"]["DecisionReject"] | components["schemas"]["DecisionRequestChanges"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Credenciales"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Sesion"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sesion_auth_sesion_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Persona"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    totales_bandeja_resumen_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InboxSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listar_bitacora_get: {
        parameters: {
            query?: {
                /** @description Filter by alert ID (UUID-like identifier) */
                alertId?: string | null;
                /** @description Filter by event type */
                type?: ("alert" | "evidence" | "proposal" | "decision" | "action" | "result" | "question" | "answer" | "refusal" | "configuracion") | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogEvent"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatQuestion"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    leer_configuracion_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    guardar_configuracion_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Settings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Settings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    obtener_consultas__query_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                query_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Query"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    crear_alerta_interno_alertas_post: {
        parameters: {
            query?: never;
            header: {
                "X-Agent": string;
                "x-agent-key": string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentAlertInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingresar_causa_interno_alertas__id__causa_put: {
        parameters: {
            query?: never;
            header: {
                "X-Agent": string;
                "X-Cost-Json"?: string | null;
                "x-agent-key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCauseInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ejecutar_accion_interno_alertas__id__ejecutar_post: {
        parameters: {
            query?: never;
            header: {
                "X-Agent": string;
                "x-agent-key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentExecutionInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingresar_propuesta_interno_alertas__id__propuesta_put: {
        parameters: {
            query?: never;
            header: {
                "X-Agent": string;
                "X-Cost-Json"?: string | null;
                "x-agent-key": string;
            };
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentProposalInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Alert"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    avanzar_simulacion_avanzar_post: {
        parameters: {
            query?: {
                dias?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dia_actual_simulacion_dia_actual_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SimulatedDay"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
